version: '3'

services:
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  server:
    container_name: server
    image: sunnielyu/pubcode-server
    ports:
      - 5000:5000
    links:
      - db:db

#  web:
#    container_name: web
#    image: ./ui
#    ports:
#      - 8000:8000